### ISSUE TITLE
Display options for Podcast/Audio 

### ISSUE THREAD

**Issue by alexfimerix** [UAMediaProd/uoa-styles#32]
Create a podcast button and display style. 
Possibly RSS feed via Discussions.

**Comment by timklapdor** [comment]
Thinking if we can get an album art + play icon and wrap the ```<audio>``` tag it would be great. Not sure if we'd need some JS though. Some ideas. 

- https://codepen.io/candroo/pen/bGNjjPZ
- https://codepen.io/ivorpad/pen/mZmYEj

**Comment by alexfimerix** [comment]
Yeah, this would be great to have within the course! I wonder about a couple things: how it might display on mobile and how the discussion feed might handle it. Keen to try it out!
