### ISSUE TITLE
adx- prefix usage

### ISSUE THREAD

**Issue by timklapdor** [UAMediaProd/uoa-styles#39]
Need to define correct usage and make consistent across the sass. At the moment it is a bit ad-hoc but we need to define if the best use. 

**Should we use adx- to just the container div/element or have adx- throughout?**

**Comment by honsaar** [comment]
.adx as a parent wrapper around our styles would work best, imo. It will match CIDILabs' usage of `<div>`s and ensures when we import the theme nothing existing breaks while we can apply it to our new builds.
