### ISSUE TITLE
Style for alternate video embed

### ISSUE THREAD

**Issue by alexfimerix** [UAMediaProd/uoa-styles#40]
Require style for video embeds from: 

- echo360
- YouTube
- Canvas native (thumbnail)

Side note: can we use CSS to update how the Canvas thumbnail displays? Currently it stinks.

**Comment by timklapdor** [comment]
Hey @alexfimerix can you create a page in a Canvas course with these three options on it? Keen to look at what we can do and if there's something I can pull together with what we have in the system.

**Comment by alexfimerix** [comment]
@timklapdor - page created here, added Studio, Echo, Native canvas and YouTube embed.

https://myuni.adelaide.edu.au/courses/67416/pages/video-types
