### ISSUE TITLE
unordered list inside step list

### ISSUE THREAD

**Issue by alexfimerix** [UAMediaProd/uoa-styles#70]
<img width="935" alt="Screen Shot 2021-12-13 at 3 55 08 pm" src="https://user-images.githubusercontent.com/27793292/145757084-e70fcc4d-335f-4f07-9528-cce26e350a12.png">

Issue with unordered lists displaying as step lists inside the step-list ol class.

**Comment by alexfimerix** [comment]
https://myuni.adelaide.edu.au/courses/69868/pages/lesson-2-how-are-managerial-decision-affected-by-culture

**Comment by timklapdor** [comment]
Added a sibling selector ```>``` to the ```li`` tags inside a ```.step-list``` and reset the text-indent to 0 for ```ul``` and ```ol``` inside an ```li``` tag.
