### ISSUE TITLE
fancy-ol counter issue

### ISSUE THREAD

**Issue by alexfimerix** [UAMediaProd/uoa-styles#71]
fancy-ol doesnt allow for a start=X number to be added due to the way it adds the box.

See: https://myuni.adelaide.edu.au/courses/69868/pages/lesson-2-what-are-the-traditional-and-contemporary-views-of-each-of-the-six-key-elements-of-organisational-design

**Comment by timklapdor** [comment]
Have added ```.broken-list``` as a class for Fancy lists - but could work on all lists. Changes the counter - so just add class to each list on the page.
