### ISSUE TITLE
padding on boxed-list

### ISSUE THREAD

**Issue by timklapdor** [UAMediaProd/uoa-styles#72]
```li``` are inside - but doesn't look goof on multi-lines. Needs a better margin/padding set. 

example: https://myuni.adelaide.edu.au/courses/69868/pages/lesson-1-what-are-the-focus-and-goals-of-organisational-behaviour-why-are-they-so-important-to-managers 

<img width="857" alt="Screen Shot 2021-12-15 at 10 50 04 pm" src="https://user-images.githubusercontent.com/4554100/146185651-5c645446-8a81-43b8-8086-395f45e4b500.png">

**Comment by honsaar** [comment]
`li` margins updated
