### ISSUE TITLE
List backgrounds

### ISSUE THREAD

**Issue by timklapdor** [UAMediaProd/uoa-styles#73]
Look at options for lists in cue boxes or activities. maybe use a transparent value.

<img width="892" alt="Screen Shot 2021-12-15 at 11 08 01 pm" src="https://user-images.githubusercontent.com/4554100/146187986-e1fc791a-574a-4b21-a497-7dde373252c5.png">

**Comment by honsaar** [comment]
Added a rule to style the background and border to match the parent `direction` class colours
