### ISSUE TITLE
New layout - icon table?

### ISSUE THREAD

**Issue by timklapdor** [UAMediaProd/uoa-styles#78]
Improve the layout here:

https://myuni.adelaide.edu.au/courses/69868/pages/lesson-3-organisational-environments?module_item_id=2496111

<img width="873" alt="Screen Shot 2021-12-23 at 8 26 30 am" src="https://user-images.githubusercontent.com/4554100/147157149-34ec2f20-f5f9-4228-9d2c-22e698c33f95.png">

**Comment by honsaar** [comment]
Will address this at same time as #76
