### ISSUE TITLE
Fix block quote margins

### ISSUE THREAD

**Issue by timklapdor** [UAMediaProd/uoa-styles#79]
As see here - maybe go ```margin: 0 auto;```

https://myuni.adelaide.edu.au/courses/69868/pages/what-to-expect-in-module-3

<img width="645" alt="Screenshot 2021-12-23 at 11 09 23 pm" src="https://user-images.githubusercontent.com/4554100/147238681-0a337d46-c021-45b5-9ae1-3464cf4999ce.png">

**Comment by honsaar** [comment]
Changes made
