### ISSUE TITLE
Fix Address Icon

### ISSUE THREAD

**Issue by timklapdor** [UAMediaProd/uoa-styles#81]
Icon next to Adelaide - should be location marker or pin. Add new SVG. 
<img width="523" alt="Screen Shot 2022-01-10 at 6 03 11 pm" src="https://user-images.githubusercontent.com/4554100/148731384-6b7db9bc-9610-421c-bbbf-b4c951534677.png">

**Comment by honsaar** [comment]
Pushed through a version of a location icon following the style of iconsvg.xyz 

![image](https://user-images.githubusercontent.com/8604678/149275004-7496df74-8366-4111-a714-bdbc9127e620.png)
